### ISSUE TITLE
Provide default constants definitions if hopcounts are activated for a TC Algorithm

### ISSUE THREAD

**Issue by davidgiessing** [eMoflon/cmoflon#25]

**Comment by RolandKluge** [comment]
// TODO@rkluge: Provide default values for
					// const-updateinterval=300,
					// const-broadcasthopcount_immediate_max = 10,
					// const-broadcasthopcount_immediate_min = 1,
					// const-broadcasthopcount_smalldelay_min = 55,
					// const-broadcasthopcount_smalldelay_max = 65,
					// const-broadcasthopcount_periodic_min = 270,
					// const-broadcasthopcount_periodic_max = 330
